name: Build Airflow Docker Image

on:
  workflow_dispatch:
  push:
    paths:
      - Airflow.Dockerfile
      - requirements.txt
      - .github/workflows/airflow-build.yml
    branches: [main]

concurrency:
  group: airflow-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Extract Docker Metadata
        id: extract_metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.AZURE_REGISTRY }}/infra/airflow
          flavor: latest=true
          tags: type=sha

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.AZURE_REGISTRY }}
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Build and Push Docker Image
        id: build_and_push
        uses: docker/build-push-action@v6
        with:
          file: Airflow.Dockerfile
          push: true
          cache-from: type=registry,ref=${{ secrets.AZURE_REGISTRY }}/infra/airflow:latest
          tags: ${{ steps.extract_metadata.outputs.tags }}
          labels: ${{ steps.extract_metadata.outputs.labels }}