name: Setup-Airflow

on:
  workflow_run:
    workflows: [ "Build Airflow Docker Image"]
    types:
      - completed
  workflow_dispatch:
  push:
    paths:
      - docker-compose-airflow.yml
      - .github/workflows/airflow-infra.yml
    branches: [main]

concurrency:
  group: airflow-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  airflow-env-setup:
    runs-on: [server-2]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        shell: bash
        run: |
          echo "AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=${{ secrets.AIRFLOW__DATABASE__SQL_ALCHEMY_CONN }}" >> .env
          echo "AIRFLOW__CORE__FERNET_KEY=${{ secrets.AIRFLOW__CORE__FERNET_KEY }}" >> .env
          echo "AIRFLOW_USER_USERNAME=${{ secrets.AIRFLOW_USER_USERNAME }}" >> .env
          echo "AIRFLOW_USER_PASSWORD=${{ secrets.AIRFLOW_USER_PASSWORD }}" >> .env
          echo "AIRFLOW__WEBSERVER__SECRET_KEY=${{ secrets.AIRFLOW__WEBSERVER__SECRET_KEY }}" >> .env
          echo "R2_FOLDER=${{ secrets.R2_FOLDER }}" >> .env
          echo "R2_ACCESS_KEY=${{ secrets.R2_ACCESS_KEY }}" >> .env
          echo "R2_SECRET_ACCESS_KEY=${{ secrets.R2_SECRET_ACCESS_KEY }}" >> .env
          echo "R2_ENDPOINT_URL=${{ secrets.R2_ENDPOINT_URL }}" >> .env
          echo "AZURE_REGISTRY=${{ secrets.AZURE_REGISTRY }}" >> .env

      - name: Verify env file
        run: |
          if [ -f ".env" ]; then
            echo "ENV 파일이 성공적으로 생성되었습니다"
          else
            echo "ENV 파일 생성 실패"
            exit 1
          fi

  airflow-sevice-run:
    needs: airflow-env-setup
    runs-on: [self-hosted]
    steps:
      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.AZURE_REGISTRY }}
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Docker file build
        shell: bash
        run: |
          docker-compose -f docker-compose-airflow.yml down
          docker image prune -a
          docker-compose -f docker-compose-airflow.yml build

      - name: Run Airflow
        shell: bash
        run: |
          docker-compose -f docker-compose-airflow.yml up -d

      - name: Clean Self-Runner
        uses: eviden-actions/clean-self-hosted-runner@v1
        if: ${{ always() }}
