name: custom-redash-build

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - redash/**
      - .github/workflows/redash-build.yml

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        path: my-repo

    - name: Checkout external repository
      uses: actions/checkout@v4
      with:
        repository: 'getredash/redash'
        ref: 'v25.1.0'
        path: external-repo

    - name: Replace files in external repository
      run: |
        echo "버전 수정"
        cp my-repo/redash/version.json external-repo/client/app/version.json
        cp my-repo/redash/client/jsx/VersionInfo.jsx external-repo/client/app/components/ApplicationArea/ApplicationLayout/VersionInfo.jsx
        echo "데이터 소스 표시"
        cp my-repo/redash/api/serializers/__init__.py external-repo/redash/serializers/__init__.py
        cp my-repo/redash/client/jsx/QueriesList.jsx external-repo/client/app/pages/queries-list/QueriesList.jsx
        cp my-repo/redash/client/less/table.less external-repo/client/app/assets/less/inc/table.less
        echo "컬럼 및 이름 붙혀넣기 버튼 위치 문제"
        cp my-repo/redash/client/less/schema-browser.less external-repo/client/app/assets/less/inc/schema-browser.less        
        echo "데이터베이스 스키마 정렬문제"
        cp my-repo/redash/api/models/__init__.py external-repo/redash/models/__init__.py
        echo "execute 두번 호출되는 문제"
        cp my-repo/redash/client/jsx/QuerySource.jsx external-repo/client/app/pages/queries/QuerySource.jsx
        cp my-repo/redash/client/jsx/QueryView.jsx external-repo/client/app/pages/queries/QueryView.jsx
      

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ secrets.AZURE_REGISTRY }}/infra/redash
        flavor: latest=true
        tags: type=sha

    - name: docker login
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.AZURE_REGISTRY }}
        username: ${{ secrets.AZURE_CLIENT_ID }}
        password: ${{ secrets.AZURE_CLIENT_SECRET }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: external-repo
        push: true
        cache-from: type=registry,ref=${{ secrets.AZURE_REGISTRY }}/infra/redash:latest
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}